<a href="https://colab.research.google.com/github/Sampritisahoo/DEEP_LEARNING/blob/main/ANN_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1st we take a random XOR dataset than we are performing ANN


In [ ]:
import numpy as np


#xor dataset

In [ ]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

#initialize weight

####Input Layer  : 2 neurons
####Hidden Layer : 3 neurons
####Output Layer : 1 neuron
####Weight matrices :W1 (Input → Hidden)shape = (2 × 3)
####W2 (Hidden → Output) shape = (3 × 1)

In [ ]:
np.random.seed(1)
w1 = np.random.randn(2,3)
#Input Layer : 2 neurons
#Hidden Layer : 3 neurons
w2 = np.random.randn(3,1)
#W2 (Hidden → Output) shape = (3 × 1)

#Activation

In [ ]:
def sigmod(x):
  return 1/(1+np.exp(-x))  #forword pro

def sigmod_derivative(x):   #backword pro(Gradient[loss propagation])
  return x*(1-x)


##Used in backpropagation to calculate gradient. It tells how much weights should change.
# training

In [ ]:
for i in range(10000):
   # -------- Feedforward --------
  Hidden_layer = sigmod(np.dot(x,w1))#→ Hidden Layer atrix multiplication:
                                    #(4×2) dot (2×3) = (4×3)Then apply sigmoid activation.

  Output = sigmod(np.dot(Hidden_layer,w2))#Hidden → Output Matrix multiplication:
  error = y-Output
  print(error)
  d_output = error*sigmod_derivative(Output)
  error_hidden = d_output.dot(w2.T)
  d_hidden = error_hidden*sigmod_derivative(Hidden_layer)
  w2 += Hidden_layer.T.dot(d_output)
  w1 += x.T.dot(d_hidden)


Streaming output truncated to the last 5000 lines.
[[-0.01555076]
 [ 0.01224267]
 [ 0.01223699]
 [-0.01708037]]
[[-0.01555062]
 [ 0.01224257]
 [ 0.01223689]
 [-0.01708022]]
[[-0.01555049]
 [ 0.01224247]
 [ 0.01223679]
 [-0.01708007]]
[[-0.01555036]
 [ 0.01224236]
 [ 0.01223668]
 [-0.01707993]]
[[-0.01555023]
 [ 0.01224226]
 [ 0.01223658]
 [-0.01707978]]
[[-0.0155501 ]
 [ 0.01224216]
 [ 0.01223648]
 [-0.01707964]]
[[-0.01554997]
 [ 0.01224205]
 [ 0.01223637]
 [-0.01707949]]
[[-0.01554984]
 [ 0.01224195]
 [ 0.01223627]
 [-0.01707935]]
[[-0.0155497 ]
 [ 0.01224185]
 [ 0.01223617]
 [-0.0170792 ]]
[[-0.01554957]
 [ 0.01224174]
 [ 0.01223606]
 [-0.01707906]]
[[-0.01554944]
 [ 0.01224164]
 [ 0.01223596]
 [-0.01707891]]
[[-0.01554931]
 [ 0.01224154]
 [ 0.01223586]
 [-0.01707877]]
[[-0.01554918]
 [ 0.01224143]
 [ 0.01223575]
 [-0.01707862]]
[[-0.01554905]
 [ 0.01224133]
 [ 0.01223565]
 [-0.01707848]]
[[-0.01554892]
 [ 0.01224123]
 [ 0.01223555]
 [-0.01707833]]
[[-0.01554878]
 [ 0.01224112]
 [ 0

In [ ]:
print("predicted output:")
print(Output)

predicted output:
[[0.01538908]
 [0.98788454]
 [0.98789009]
 [0.01690184]]
